name = "ClimateDatasets"
uuid = "57ad8bab-f6f8-48cd-9c24-8d5a3bf73d4f"
authors = ["James Doss-Gollin <jdossgollin@rice.edu>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
