# some parameters to control the ERA5 reanalysis data
era5:
  first_year: 1940
  last_year: 2024
  vars:
    pressure_level:
        - name: u_component_of_wind
          levels:
            - 500
        - name: v_component_of_wind
          levels: 
            - 500
    single_level:
      - vertical_integral_of_eastward_water_vapour_flux
      - vertical_integral_of_northward_water_vapour_flux
      - 2m_temperature

bbox:
  - name: "CONUS"
    lon_min: -125
    lon_max: -65
    lat_min: 25
    lat_max: 50
    resolution: 0.25